Second stage
SweetD0blE/java-explore-with-me pull request #5
Opened 2023-09-01 20:31 UTC by SweetD0blE

2023-09-02 01:32 UTC, SweetD0blE commented
Это было тяжело...

2023-09-02 09:17 UTC, sergeymamonov requested changes
В качестве улучшения классы dto можно сделать иммутабельными. Можно добавить final к классу и добавить условие в @FieldDefaults.

2023-09-02 09:17 UTC, sergeymamonov commented on ewm-main-service/src/main/java/ru/practicum/ewm/main_service/request/service/RequestServiceImpl.java
> +            requests.stream().forEach(request -> {
stream().forEach - избыточная конструкция. Можно с помощью одного из этих двух операторов сделать.

2023-09-02 09:17 UTC, sergeymamonov commented on ewm-main-service/src/main/java/ru/practicum/ewm/main_service/MainCommon.java
> +    public static final DateTimeFormatter DT_FORMATTER = DateTimeFormatter.ofPattern(DT_FORMAT);
Какие из этих констант используются?

2023-09-02 09:17 UTC, sergeymamonov commented on ewm-stats-service/common-dto/src/main/java/ru/practicum/ewm/common_dto/EndpointHitDto.java
> -    private final String app;
При замене на @FieldDefaults(level = AccessLevel.PRIVATE) потерялся модификатор final. Посмотрите, как добавить этот модификатор в аннотацию.

2023-09-02 09:17 UTC, sergeymamonov commented on ewm-stats-service/stats-client/src/main/java/ru/practicum/ewm/stats_client/StatsClient.java
> +        } catch (Exception ex) {
Отлавливать просто Exception это не очень хорошо. Нужно отлавливать конкретную ошибку, которую может кинуть код внутри блока try.

2023-09-02 09:17 UTC, sergeymamonov commented on ewm-stats-service/stats-client/src/main/java/ru/practicum/ewm/stats_client/StatsClient.java
> +                .uriTemplateHandler(new DefaultUriBuilderFactory("http://stats-server:9090"))
Лучше адрес в константу или даже в ресурсный файл.

2023-09-02 09:17 UTC, sergeymamonov commented on ewm-stats-service/stats-server/src/main/java/ru/practicum/ewm/stats_server/exception/ErrorHandler.java
> +}
Лучше еще сделать обработку RuntimeException.

2023-09-02 22:42 UTC, SweetD0blE commented
Добрый вечер. Постарался пофиксить все ошибки. По поводу объекта - да, так удобнее выглядит, но под мой код не получилось подстроить это, времени мало.. Последний день остался, очень хочется закрыть всё)

2023-09-03 12:05 UTC, sergeymamonov commented
> В качестве улучшения классы dto можно сделать иммутабельными. Можно добавить final к классу и добавить условие в @FieldDefaults.

@FieldDefaults(makeFinal=true, level=AccessLevel.PRIVATE)

2023-09-03 13:13 UTC, sergeymamonov approved these changes

2023-09-03 13:13 UTC, sergeymamonov commented on ewm-stats-service/stats-client/src/main/java/ru/practicum/ewm/stats_client/StatsClient.java
> +        } catch (RuntimeException ex) {
Отлавливая RuntimeException, вы отлавливаете группу ошибок сразу, то есть все ошибки, которые наследуются от RuntimeException. Посмотрите иерархию ошибок. Нужно отлавливать именно ту ошибку, которую может кинуть код внутри блока try.

2023-09-03 13:13 UTC, sergeymamonov commented on ewm-stats-service/stats-client/src/main/java/ru/practicum/ewm/stats_client/StatsClient.java
> +    public static final String HTTP = "http://stats-server:9090";
STATS_SERVER_URL более информативное название для константы.

2023-09-03 13:13 UTC, sergeymamonov commented on ewm-stats-service/stats-server/src/main/java/ru/practicum/ewm/stats_server/service/StatsServiceImpl.java
> +        if (uris == null || uris.size() == 0 || uris.get(0).equals("events/") || uris.get(0).isBlank()) {
Не исправлено.

2023-09-03 16:24 UTC, merged